const wordData = {
    1: [
        { s: "時間をずらしたい時", j: "〜を延期する", e: "Postpone", d: ["Cancel", "Hurry", "Avoid"], p: "Can we postpone the meeting?" },
        { s: "日程を組み直す時", j: "〜の予定を変更する", e: "Reschedule", d: ["Confirm", "Repeat", "Reduce"], p: "I need to reschedule our appointment." },
        { s: "忙しい時", j: "手が離せない", e: "Be tied up", d: ["Be free", "Be ready", "Be late"], p: "I'm tied up at the moment." },
        { s: "人を迎えに行く時", j: "（人を）迎えに行く", e: "Pick up", d: ["Drop off", "Look for", "Take out"], p: "I'll pick you up at 7." },
        { s: "情報を調べる時", j: "（辞書等で）調べる", e: "Look up", d: ["Look at", "Look for", "Look after"], p: "Let me look up the word." },
        { s: "近況を教える時", j: "〜を更新する", e: "Update", d: ["Upload", "Upgrade", "Upsize"], p: "I'll update you on the project." },
        { s: "対処できると言う時", j: "〜を扱う、対処する", e: "Handle", d: ["Hold", "Help", "Hear"], p: "I can handle this situation." },
        { s: "意味をはっきりさせたい時", j: "〜を明確にする", e: "Clarify", d: ["Classify", "Clean", "Close"], p: "Could you clarify that point?" },
        { s: "招待などを受ける時", j: "〜を受け入れる", e: "Accept", d: ["Refuse", "Expect", "Access"], p: "I accept your invitation." },
        { s: "事実を確かめる時", j: "〜を確認する", e: "Confirm", d: ["Conform", "Confuse", "Conflict"], p: "Let me confirm the details." },
        { s: "連絡を取り合いたい時", j: "連絡を保つ", e: "Keep in touch", d: ["Take a look", "Stay away", "Get back"], p: "Let's keep in touch." },
        { s: "理由を話す時", j: "〜を説明する", e: "Explain", d: ["Explore", "Express", "Expect"], p: "Let me explain why." },
        { s: "賛成する時", j: "〜に同意する", e: "Agree", d: ["Deny", "Offer", "Apply"], p: "I agree with you." },
        { s: "仲間に加わる時", j: "〜に参加する", e: "Join", d: ["Enjoy", "Job", "Joke"], p: "Would you like to join us?" },
        { s: "書類を出す時", j: "〜を提出する", e: "Submit", d: ["Subject", "Subscribe", "Sublet"], p: "Please submit the report." },
        { s: "解決策を考える時", j: "（考えて）解決する", e: "Figure out", d: ["Fill out", "Find out", "Look for"], p: "We need to figure out a way." },
        { s: "検討をお願いする時", j: "〜を検討する", e: "Consider", d: ["Contact", "Continue", "Contain"], p: "Please consider our offer." },
        { s: "準備中の時", j: "〜を準備する", e: "Prepare", d: ["Repair", "Compare", "Prevent"], p: "I'm preparing for it." },
        { s: "確認作業をする時", j: "〜をチェックする", e: "Check", d: ["Choose", "Change", "Charge"], p: "Let me check the list." },
        { s: "ついでに寄る時", j: "（場所へ）立ち寄る", e: "Stop by", d: ["Stop up", "Stop off", "Stop over"], p: "I'll stop by your office." }
    ],
    2: [
        { s: "意見を言う時", j: "〜に言及する", e: "Mention", d: ["Maintain", "Manage", "Measure"], p: "He mentioned the plan." },
        { s: "会議を開く時", j: "〜を開催する", e: "Hold", d: ["Help", "Hope", "Halt"], p: "We will hold a meeting." },
        { s: "期待している時", j: "〜を期待する", e: "Expect", d: ["Except", "Expert", "Export"], p: "I expect a good result." },
        { s: "必要なものがある時", j: "〜を必要とする", e: "Require", d: ["Request", "Retire", "Repair"], p: "This requires patience." },
        { s: "申し込む時", j: "〜に申し込む", e: "Apply", d: ["Approve", "Appoint", "Appear"], p: "I want to apply for the job." },
        { s: "提案する時", j: "〜を提案する", e: "Suggest", d: ["Support", "Suppose", "Suffer"], p: "I suggest we take a break." },
        { s: "手配する時", j: "〜を手配する", e: "Arrange", d: ["Arrive", "Arrest", "Argue"], p: "I'll arrange the flight." },
        { s: "避けるべき時", j: "〜を避ける", e: "Avoid", d: ["Afford", "Advice", "Admit"], p: "Avoid heavy traffic." },
        { s: "減らしたい時", j: "〜を減らす", e: "Reduce", d: ["Refuse", "Recycle", "Remove"], p: "We should reduce costs." },
        { s: "改善したい時", j: "〜を改善する", e: "Improve", d: ["Import", "Impress", "Imply"], p: "I want to improve my English." },
        { s: "何かを終える時", j: "〜を完了する", e: "Complete", d: ["Compare", "Compete", "Complex"], p: "The project is complete." },
        { s: "準備ができている時", j: "〜が利用できる", e: "Available", d: ["Average", "Avoidable", "Assistant"], p: "I'm available tomorrow." },
        { s: "提供したい時", j: "〜を提供する", e: "Provide", d: ["Prevent", "Promote", "Protect"], p: "We provide help." },
        { s: "解決策がある時", j: "〜を解決する", e: "Solve", d: ["Sold", "Soft", "Sole"], p: "We can solve this." },
        { s: "誰かを助ける時", j: "〜を支援する", e: "Support", d: ["Suppose", "Surprise", "Supply"], p: "Thanks for your support." },
        { s: "意見を聞く時", j: "〜に同意する", e: "Agree", d: ["Argue", "Accept", "Apply"], p: "I agree with you." },
        { s: "計画を立てる時", j: "〜を決定する", e: "Decide", d: ["Divide", "Describe", "Detail"], p: "I'll decide later." },
        { s: "目標がある時", j: "達成する", e: "Achieve", d: ["Archive", "Active", "Advance"], p: "You can achieve it." },
        { s: "勧めたい時", j: "〜を推薦する", e: "Recommend", d: ["Record", "Recall", "Remind"], p: "I recommend this book." },
        { s: "頼み事をする時", j: "〜を要求する", e: "Request", d: ["Respect", "Refuse", "Repeat"], p: "I'll request a meeting." }
    ],
    3: [
        { s: "誰かを誘う時", j: "〜を招待する", e: "Invite", d: ["Invent", "Invest", "Involve"], p: "Let me invite you to lunch." },
        { s: "新しい導入", j: "〜を紹介する・導入する", e: "Introduce", d: ["Include", "Indicate", "Increase"], p: "I'll introduce our new team." },
        { s: "許可を得る時", j: "〜を許可する", e: "Allow", d: ["Avoid", "Apply", "Appear"], p: "Please allow me to go." },
        { s: "荷物を送る時", j: "〜を届ける", e: "Deliver", d: ["Develop", "Depart", "Design"], p: "We deliver to your home." },
        { s: "過去を思い出す", j: "〜を覚えている", e: "Remember", d: ["Remind", "Remove", "Repair"], p: "I remember that day." },
        { s: "気づいた時", j: "〜に気づく", e: "Notice", d: ["Note", "Notify", "Noisy"], p: "Did you notice the sign?" },
        { s: "ネットで探す", j: "〜を検索する", e: "Search", d: ["Select", "Settle", "Share"], p: "Search it on the web." },
        { s: "皆で使う時", j: "〜を共有する", e: "Share", d: ["Shape", "Sharp", "Short"], p: "Share your ideas with us." },
        { s: "満足させる", j: "〜を満足させる", e: "Satisfy", d: ["Safety", "Sample", "Saving"], p: "We satisfy our clients." },
        { s: "準備万端にする", j: "〜を準備する", e: "Prepare", d: ["Prevent", "Present", "Predict"], p: "Prepare for the trip." },
        { s: "壊れたものを直す", j: "〜を修理する", e: "Repair", d: ["Replace", "Report", "Repeat"], p: "Repair the broken chair." },
        { s: "新品と替える", j: "〜を交換する", e: "Replace", d: ["Repeat", "Repair", "Reply"], p: "Replace the old parts." },
        { s: "メールの返事", j: "〜に返事をする", e: "Reply", d: ["Report", "Repeat", "Replace"], p: "Please reply to my mail." },
        { s: "状況を伝える", j: "〜を報告する", e: "Report", d: ["Repeat", "Repair", "Reply"], p: "Report the sales result." },
        { s: "もう一度言う", j: "〜を繰り返す", e: "Repeat", d: ["Report", "Repair", "Reply"], p: "Repeat after me." },
        { s: "席を確保する", j: "〜を予約する", e: "Reserve", d: ["Respect", "Result", "Return"], p: "Reserve a hotel room." },
        { s: "人を敬う", j: "〜を尊敬する", e: "Respect", d: ["Reserve", "Result", "Return"], p: "Respect each other." },
        { s: "テストの結末", j: "結果", e: "Result", d: ["Reserve", "Respect", "Return"], p: "The result was good." },
        { s: "場所に戻る", j: "〜を返す、戻る", e: "Return", d: ["Reserve", "Respect", "Result"], p: "Return to the office." },
        { s: "物を受け取る", j: "〜を受け取る", e: "Receive", d: ["Reduce", "Refuse", "Recycle"], p: "Receive a gift." }
    ],
    4: [
        { s: "きっぱり断る", j: "〜を拒絶する", e: "Refuse", d: ["Reduce", "Recycle", "Receive"], p: "He refused the offer." },
        { s: "コストを削る", j: "〜を減らす", e: "Reduce", d: ["Refuse", "Recycle", "Receive"], p: "Reduce the cost." },
        { s: "資源を回す", j: "〜を再利用する", e: "Recycle", d: ["Reduce", "Refuse", "Receive"], p: "Recycle paper." },
        { s: "状態を保つ", j: "〜を維持する", e: "Maintain", d: ["Mention", "Manage", "Measure"], p: "Maintain the garden." },
        { s: "人を動かす", j: "〜を管理する", e: "Manage", d: ["Maintain", "Mention", "Measure"], p: "Manage a project." },
        { s: "長さをはかる", j: "〜を測定する", e: "Measure", d: ["Maintain", "Mention", "Manage"], p: "Measure the size." },
        { s: "頭に描く", j: "〜を想像する", e: "Imagine", d: ["Improve", "Import", "Impress"], p: "Imagine your future." },
        { s: "感動させる", j: "〜に感銘を与える", e: "Impress", d: ["Imagine", "Improve", "Import"], p: "Impress the guests." },
        { s: "外から入れる", j: "〜を輸入する", e: "Import", d: ["Imagine", "Improve", "Impress"], p: "Import fruits." },
        { s: "腕を上げる", j: "〜を改善する", e: "Improve", d: ["Imagine", "Import", "Impress"], p: "Improve your skills." },
        { s: "先を読み期待する", j: "〜を期待する", e: "Anticipate", d: ["Accept", "Achieve", "Advance"], p: "Anticipate changes." },
        { s: "オファーを飲む", j: "〜を受け入れる", e: "Accept", d: ["Anticipate", "Achieve", "Advance"], p: "Accept the deal." },
        { s: "やり遂げる", j: "〜を達成する", e: "Achieve", d: ["Anticipate", "Accept", "Advance"], p: "Achieve the goal." },
        { s: "前へ進む", j: "〜を進歩させる", e: "Advance", d: ["Anticipate", "Accept", "Achieve"], p: "Advance your career." },
        { s: "大勢に伝える", j: "〜を発表する", e: "Announce", d: ["Apply", "Appear", "Approve"], p: "Announce the winner." },
        { s: "願書を出す", j: "〜に申し込む", e: "Apply", d: ["Announce", "Appear", "Approve"], p: "Apply for a job." },
        { s: "姿を見せる", j: "現れる", e: "Appear", d: ["Announce", "Apply", "Approve"], p: "A star appeared." },
        { s: "許可を出す", j: "〜を承認する", e: "Approve", d: ["Announce", "Apply", "Appear"], p: "Approve the plan." },
        { s: "言い争う", j: "〜を議論する", e: "Argue", d: ["Arrive", "Arrange", "Arrest"], p: "Don't argue with me." },
        { s: "駅に着く", j: "到着する", e: "Arrive", d: ["Argue", "Arrange", "Arrest"], p: "Arrive at the station." }
    ],
    // 5〜15章は日常・ビジネス・旅行・感情の重要語を網羅しています
    5: [
        { s: "行動を促す", j: "〜を励ます", e: "Encourage", d: ["Enable", "Enjoy", "Enlarge"], p: "Encourage my friend." },
        { s: "可能にする", j: "〜を可能にする", e: "Enable", d: ["Encourage", "Ensure", "Enforce"], p: "Enable the setting." },
        { s: "確実にする", j: "〜を確実にする", e: "Ensure", d: ["Enable", "Endure", "Enlarge"], p: "Ensure safety." },
        { s: "楽しむ", j: "〜を楽しむ", e: "Enjoy", d: ["Encourage", "Enlarge", "Enable"], p: "Enjoy the party." },
        { s: "広げる", j: "〜を大きくする", e: "Enlarge", d: ["Enjoy", "Ensure", "Enable"], p: "Enlarge the photo." },
        { s: "人を信じる", j: "〜を信頼する", e: "Trust", d: ["Try", "Travel", "Treat"], p: "I trust you." },
        { s: "人を扱う", j: "〜を扱う", e: "Treat", d: ["Trust", "Track", "Trade"], p: "Treat people well." },
        { s: "商売をする", j: "貿易・取引", e: "Trade", d: ["Treat", "Track", "Trust"], p: "Free trade." },
        { s: "跡を追う", j: "〜を追跡する", e: "Track", d: ["Trade", "Treat", "Trust"], p: "Track the package." },
        { s: "旅行する", j: "旅行する", e: "Travel", d: ["Track", "Trade", "Trust"], p: "Travel around the world." },
        { s: "誰かを呼ぶ", j: "〜を呼ぶ", e: "Call", d: ["Care", "Carry", "Catch"], p: "Call me later." },
        { s: "気遣う", j: "〜を気にする", e: "Care", d: ["Call", "Carry", "Catch"], p: "I don't care." },
        { s: "物を運ぶ", j: "〜を運ぶ", e: "Carry", d: ["Call", "Care", "Catch"], p: "Carry the bag." },
        { s: "ボールを捕る", j: "〜を捕まえる", e: "Catch", d: ["Call", "Care", "Carry"], p: "Catch the ball." },
        { s: "理由を尋ねる", j: "〜の原因となる", e: "Cause", d: ["Case", "Cash", "Cast"], p: "Cause a problem." },
        { s: "変化させる", j: "〜を変える", e: "Change", d: ["Charge", "Choose", "Check"], p: "Change your mind." },
        { s: "代金を請求する", j: "〜を請求する", e: "Charge", d: ["Change", "Choose", "Check"], p: "Charge the fee." },
        { s: "選ぶ", j: "〜を選ぶ", e: "Choose", d: ["Change", "Charge", "Check"], p: "Choose one." },
        { s: "確認する", j: "〜を確認する", e: "Check", d: ["Change", "Charge", "Choose"], p: "Check the time." },
        { s: "きれいに刷る", j: "〜を掃除する", e: "Clean", d: ["Clear", "Close", "Climb"], p: "Clean the room." }
    ],
    6: [
        { s: "はっきりさせる", j: "明らかな", e: "Clear", d: ["Clean", "Close", "Climb"], p: "It's clear now." },
        { s: "ドアを閉める", j: "〜を閉める", e: "Close", d: ["Clean", "Clear", "Climb"], p: "Close the door." },
        { s: "山に登る", j: "〜に登る", e: "Climb", d: ["Clean", "Clear", "Close"], p: "Climb the mountain." },
        { s: "物を集める", j: "〜を集める", e: "Collect", d: ["Color", "Come", "Common"], p: "Collect stamps." },
        { s: "やって来る", j: "来る", e: "Come", d: ["Collect", "Color", "Common"], p: "Come here." },
        { s: "共通の", j: "共通の", e: "Common", d: ["Collect", "Color", "Come"], p: "Common sense." },
        { s: "比べる", j: "〜を比較する", e: "Compare", d: ["Compete", "Complete", "Complain"], p: "Compare two things." },
        { s: "競い合う", j: "〜と競争する", e: "Compete", d: ["Compare", "Complete", "Complain"], p: "Compete with others." },
        { s: "文句を言う", j: "不平を言う", e: "Complain", d: ["Compare", "Compete", "Complete"], p: "Don't complain." },
        { s: "やり切る", j: "〜を完了する", e: "Complete", d: ["Compare", "Compete", "Complain"], p: "Complete the task." },
        { s: "集中する", j: "〜に集中する", e: "Concentrate", d: ["Concern", "Conclude", "Confirm"], p: "Concentrate on study." },
        { s: "心配する", j: "〜を心配させる", e: "Concern", d: ["Concentrate", "Conclude", "Confirm"], p: "Public concern." },
        { s: "結論づける", j: "〜と結論を出す", e: "Conclude", d: ["Concentrate", "Concern", "Confirm"], p: "To conclude my talk." },
        { s: "はっきり認める", j: "〜を確認する", e: "Confirm", d: ["Concentrate", "Concern", "Conclude"], p: "Confirm the flight." },
        { s: "つなぐ", j: "〜を接続する", e: "Connect", d: ["Contact", "Contain", "Continue"], p: "Connect to the Wi-Fi." },
        { s: "連絡する", j: "〜に連絡する", e: "Contact", d: ["Connect", "Contain", "Continue"], p: "Contact the office." },
        { s: "中に含む", j: "〜を含む", e: "Contain", d: ["Connect", "Contact", "Continue"], p: "Contain sugar." },
        { s: "やり続ける", j: "〜を続ける", e: "Continue", d: ["Connect", "Contact", "Contain"], p: "Continue the work." },
        { s: "操る", j: "〜を制御する", e: "Control", d: ["Convert", "Cook", "Copy"], p: "Control the volume." },
        { s: "変える", j: "〜を転換する", e: "Convert", d: ["Control", "Cook", "Copy"], p: "Convert files." }
    ],
    7: [
        { s: "料理する", j: "〜を料理する", e: "Cook", d: ["Control", "Convert", "Copy"], p: "Cook dinner." },
        { s: "写しを取る", j: "〜を複写する", e: "Copy", d: ["Control", "Convert", "Cook"], p: "Copy the page." },
        { s: "正す", j: "正しい、〜を直す", e: "Correct", d: ["Cost", "Count", "Cover"], p: "Correct the error." },
        { s: "費用がかかる", j: "費用、〜がかかる", e: "Cost", d: ["Correct", "Count", "Cover"], p: "It costs much." },
        { s: "数をかぞえる", j: "〜を数える", e: "Count", d: ["Correct", "Cost", "Cover"], p: "Count the numbers." },
        { s: "覆う", j: "〜を覆う", e: "Cover", d: ["Correct", "Cost", "Count"], p: "Cover the table." },
        { s: "作る", j: "〜を創造する", e: "Create", d: ["Cross", "Cry", "Cut"], p: "Create a new app." },
        { s: "道を渡る", j: "〜を横切る", e: "Cross", d: ["Create", "Cry", "Cut"], p: "Cross the street." },
        { s: "泣く", j: "泣く", e: "Cry", d: ["Create", "Cross", "Cut"], p: "Don't cry." },
        { s: "切る", j: "〜を切る", e: "Cut", d: ["Create", "Cross", "Cry"], p: "Cut the paper." },
        { s: "踊る", j: "踊る", e: "Dance", d: ["Dare", "Deal", "Decide"], p: "Dance with me." },
        { s: "あえて〜する", j: "あえて〜する", e: "Dare", d: ["Dance", "Deal", "Decide"], p: "How dare you!" },
        { s: "扱う", j: "〜を扱う、取引", e: "Deal", d: ["Dance", "Dare", "Decide"], p: "Deal with problems." },
        { s: "決める", j: "〜を決定する", e: "Decide", d: ["Dance", "Dare", "Deal"], p: "Decide the date." },
        { s: "宣言する", j: "〜を宣言する", e: "Declare", d: ["Decline", "Decorate", "Decrease"], p: "Declare victory." },
        { s: "断る・減る", j: "〜を断る、下落する", e: "Decline", d: ["Declare", "Decorate", "Decrease"], p: "Decline the invite." },
        { s: "飾る", j: "〜を飾る", e: "Decorate", d: ["Declare", "Decline", "Decrease"], p: "Decorate the room." },
        { s: "減らす", j: "〜を減少させる", e: "Decrease", d: ["Declare", "Decline", "Decorate"], p: "Decrease the speed." },
        { s: "打ち負かす", j: "〜を負かす", e: "Defeat", d: ["Defend", "Define", "Delay"], p: "Defeat the enemy." },
        { s: "守る", j: "〜を守る", e: "Defend", d: ["Defeat", "Define", "Delay"], p: "Defend the city." }
    ],
    8: [
        { s: "定義する", j: "〜を定義する", e: "Define", d: ["Defeat", "Defend", "Delay"], p: "Define the word." },
        { s: "遅らせる", j: "〜を遅らせる", e: "Delay", d: ["Defeat", "Defend", "Define"], p: "Sorry for the delay." },
        { s: "届ける", j: "〜を配達する", e: "Deliver", d: ["Demand", "Deny", "Depend"], p: "Deliver the pizza." },
        { s: "要求する", j: "〜を強く要求する", e: "Demand", d: ["Deliver", "Deny", "Depend"], p: "High demand." },
        { s: "否定する", j: "〜を否定する", e: "Deny", d: ["Deliver", "Demand", "Depend"], p: "He denied it." },
        { s: "頼る", j: "〜に依存する", e: "Depend", d: ["Deliver", "Demand", "Deny"], p: "Depend on you." },
        { s: "描写する", j: "〜を描写する", e: "Describe", d: ["Deserve", "Design", "Destroy"], p: "Describe the man." },
        { s: "値する", j: "〜に値する", e: "Deserve", d: ["Describe", "Design", "Destroy"], p: "You deserve it." },
        { s: "設計する", j: "〜を設計する", e: "Design", d: ["Describe", "Deserve", "Destroy"], p: "Design a house." },
        { s: "壊す", j: "〜を破壊する", e: "Destroy", d: ["Describe", "Deserve", "Design"], p: "Destroy the building." },
        { s: "詳細", j: "詳細", e: "Detail", d: ["Detect", "Determine", "Develop"], p: "Tell me the details." },
        { s: "見つける", j: "〜を感知する", e: "Detect", d: ["Detail", "Determine", "Develop"], p: "Detect a virus." },
        { s: "決心する", j: "〜を決定する", e: "Determine", d: ["Detail", "Detect", "Develop"], p: "Determine the cause." },
        { s: "開発する", j: "〜を発展させる", e: "Develop", d: ["Detail", "Detect", "Determine"], p: "Develop new products." },
        { s: "捧げる", j: "〜を捧げる", e: "Devote", d: ["Dial", "Dictate", "Differ"], p: "Devote my life." },
        { s: "電話をかける", j: "〜にダイヤルする", e: "Dial", d: ["Devote", "Dictate", "Differ"], p: "Dial the number." },
        { s: "書き取らせる", j: "〜を書き取らせる", e: "Dictate", d: ["Devote", "Dial", "Differ"], p: "Dictate a letter." },
        { s: "異なる", j: "異なる", e: "Differ", d: ["Devote", "Dial", "Dictate"], p: "They differ in color." },
        { s: "掘る", j: "〜を掘る", e: "Dig", d: ["Direct", "Disagree", "Disappear"], p: "Dig a hole." },
        { s: "指示する", j: "直接の、〜を指示する", e: "Direct", d: ["Dig", "Disagree", "Disappear"], p: "Direct contact." }
    ],
    9: [
        { s: "反対する", j: "意見が合わない", e: "Disagree", d: ["Dig", "Direct", "Disappear"], p: "I disagree with you." },
        { s: "消える", j: "見えなくなる", e: "Disappear", d: ["Dig", "Direct", "Disagree"], p: "The cat disappeared." },
        { s: "がっかりさせる", j: "〜を失望させる", e: "Disappoint", d: ["Discard", "Discover", "Discuss"], p: "Don't disappoint me." },
        { s: "捨てる", j: "〜を捨てる", e: "Discard", d: ["Disappoint", "Discover", "Discuss"], p: "Discard old clothes." },
        { s: "見つける", j: "〜を発見する", e: "Discover", d: ["Disappoint", "Discard", "Discuss"], p: "Discover a secret." },
        { s: "話し合う", j: "〜を議論する", e: "Discuss", d: ["Disappoint", "Discard", "Discover"], p: "Discuss the plan." },
        { s: "展示する", j: "〜を展示する", e: "Display", d: ["Distinguish", "Distribute", "Disturb"], p: "Display the art." },
        { s: "区別する", j: "〜を区別する", e: "Distinguish", d: ["Display", "Distribute", "Disturb"], p: "Distinguish right from wrong." },
        { s: "配る", j: "〜を分配する", e: "Distribute", d: ["Display", "Distinguish", "Disturb"], p: "Distribute flyers." },
        { s: "邪魔する", j: "〜を妨げる", e: "Disturb", d: ["Display", "Distinguish", "Distribute"], p: "Do not disturb." },
        { s: "分ける", j: "〜を分ける", e: "Divide", d: ["Do", "Donate", "Double"], p: "Divide the cake." },
        { s: "する", j: "〜をする", e: "Do", d: ["Divide", "Donate", "Double"], p: "Do your best." },
        { s: "寄付する", j: "〜を寄付する", e: "Donate", d: ["Divide", "Do", "Double"], p: "Donate money." },
        { s: "2倍にする", j: "2倍の", e: "Double", d: ["Divide", "Do", "Donate"], p: "Double check." },
        { s: "疑う", j: "〜を疑う", e: "Doubt", d: ["Drag", "Draw", "Dream"], p: "I doubt it." },
        { s: "引きずる", j: "〜を引きずる", e: "Drag", d: ["Doubt", "Draw", "Dream"], p: "Drag and drop." },
        { s: "描く・引く", j: "〜を描く、引く", e: "Draw", d: ["Doubt", "Drag", "Dream"], p: "Draw a map." }

        10: [
        { s: "落とす", j: "〜を落とす", e: "Drop", d: ["Drink", "Drive", "Dry"], p: "Drop the phone." },
        { s: "乾かす", j: "乾いた、〜を乾かす", e: "Dry", d: ["Drink", "Drive", "Drop"], p: "Dry the hair." },
        { s: "稼ぐ", j: "〜を稼ぐ", e: "Earn", d: ["Ease", "Eat", "Echo"], p: "Earn money." },
        { s: "楽にする", j: "容易さ、〜を和らげる", e: "Ease", d: ["Earn", "Eat", "Echo"], p: "Ease the pain." },
        { s: "食べる", j: "〜を食べる", e: "Eat", d: ["Earn", "Ease", "Echo"], p: "Eat lunch." },
        { s: "響く", j: "こだま、〜を繰り返す", e: "Echo", d: ["Earn", "Ease", "Eat"], p: "Voices echo." },
        { s: "編集する", j: "〜を編集する", e: "Edit", d: ["Educate", "Effect", "Elect"], p: "Edit the video." },
        { s: "教育する", j: "〜を教育する", e: "Educate", d: ["Edit", "Effect", "Elect"], p: "Educate children." },
        { s: "影響", j: "効果、影響", e: "Effect", d: ["Edit", "Educate", "Elect"], p: "Side effect." },
        { s: "選ぶ（選挙）", j: "〜を選挙する", e: "Elect", d: ["Edit", "Educate", "Effect"], p: "Elect a leader." },
        { s: "強調する", j: "〜を強調する", e: "Emphasize", d: ["Employ", "Empty", "Enable"], p: "Emphasize the point." },
        { s: "雇う", j: "〜を雇う", e: "Employ", d: ["Emphasize", "Empty", "Enable"], p: "Employ workers." },
        { s: "空の", j: "空の、〜を空にする", e: "Empty", d: ["Emphasize", "Employ", "Enable"], p: "An empty box." },
        { s: "励ます", j: "〜を勇気づける", e: "Encourage", d: ["End", "Endure", "Engage"], p: "Encourage a player." },
        { s: "終わる", j: "終わり、〜を終える", e: "End", d: ["Encourage", "Endure", "Engage"], p: "End of story." },
        { s: "耐える", j: "〜に耐える", e: "Endure", d: ["Encourage", "End", "Engage"], p: "Endure the cold." },
        { s: "従事する", j: "〜を従事させる", e: "Engage", d: ["Encourage", "End", "Endure"], p: "Engage in work." },
        { s: "楽しむ", j: "〜を楽しむ", e: "Enjoy", d: ["Enlarge", "Enlighten", "Ensure"], p: "Enjoy the trip." },
        { s: "大きくする", j: "〜を拡大する", e: "Enlarge", d: ["Enjoy", "Enlighten", "Ensure"], p: "Enlarge the map." },
        { s: "確実にする", j: "〜を確実にする", e: "Ensure", d: ["Enjoy", "Enlarge", "Enlighten"], p: "Ensure safety." }
    ],
    11: [
        { s: "入る", j: "〜に入る", e: "Enter", d: ["Entertain", "Envy", "Equal"], p: "Enter the room." },
        { s: "楽しませる", j: "〜を楽しまる", e: "Entertain", d: ["Enter", "Envy", "Equal"], p: "Entertain guests." },
        { s: "うらやむ", j: "〜をうらやむ", e: "Envy", d: ["Enter", "Entertain", "Equal"], p: "I envy you." },
        { s: "等しい", j: "等しい、〜に匹敵する", e: "Equal", d: ["Enter", "Entertain", "Envy"], p: "Equal rights." },
        { s: "消す", j: "〜を消す", e: "Erase", d: ["Escape", "Establish", "Estimate"], p: "Erase the board." },
        { s: "逃げる", j: "〜を逃れる", e: "Escape", d: ["Erase", "Establish", "Estimate"], p: "Escape from danger." },
        { s: "設立する", j: "〜を確立する", e: "Establish", d: ["Erase", "Escape", "Estimate"], p: "Establish a firm." },
        { s: "見積もる", j: "〜を推定する", e: "Estimate", d: ["Erase", "Escape", "Establish"], p: "Estimate the cost." },
        { s: "評価する", j: "〜を評価する", e: "Evaluate", d: ["Exaggerate", "Examine", "Exceed"], p: "Evaluate results." },
        { s: "大げさに言う", j: "〜を誇張する", e: "Exaggerate", d: ["Evaluate", "Examine", "Exceed"], p: "Don't exaggerate." },
        { s: "調べる", j: "〜を調査する", e: "Examine", d: ["Evaluate", "Exaggerate", "Exceed"], p: "Examine the patient." },
        { s: "超える", j: "〜を超える", e: "Exceed", d: ["Evaluate", "Exaggerate", "Examine"], p: "Exceed the limit." },
        { s: "交換する", j: "〜を交換する", e: "Exchange", d: ["Excite", "Exclude", "Excuse"], p: "Exchange money." },
        { s: "興奮させる", j: "〜をわくわくさせる", e: "Excite", d: ["Exchange", "Exclude", "Excuse"], p: "Exciting news." },
        { s: "除外する", j: "〜を排除する", e: "Exclude", d: ["Exchange", "Excite", "Excuse"], p: "Exclude tax." },
        { s: "言い訳・許す", j: "言い訳、〜を許す", e: "Excuse", d: ["Exchange", "Excite", "Exclude"], p: "Excuse me." },
        { s: "実行する", j: "〜を実行する", e: "Execute", d: ["Exercise", "Exhibit", "Exist"], p: "Execute the plan." },
        { s: "運動する", j: "運動、〜を練習する", e: "Exercise", d: ["Execute", "Exhibit", "Exist"], p: "Daily exercise." },
        { s: "展示する", j: "〜を展示する", e: "Exhibit", d: ["Execute", "Exercise", "Exist"], p: "Exhibit the works." },
        { s: "存在する", j: "存在する", e: "Exist", d: ["Execute", "Exercise", "Exhibit"], p: "Does God exist?" }
    ],
    12: [
        { s: "広がる", j: "〜を拡大する", e: "Expand", d: ["Expect", "Expel", "Expend"], p: "Expand the business." },
        { s: "期待する", j: "〜を予期する", e: "Expect", d: ["Expand", "Expel", "Expend"], p: "Expect a baby." },
        { s: "追い出す", j: "〜を追放する", e: "Expel", d: ["Expand", "Expect", "Expend"], p: "Expel a student." },
        { s: "費やす", j: "〜を費やす", e: "Expend", d: ["Expand", "Expect", "Expel"], p: "Expend energy." },
        { s: "経験する", j: "経験、〜を経験する", e: "Experience", d: ["Explain", "Explode", "Explore"], p: "Work experience." },
        { s: "説明する", j: "〜を説明する", e: "Explain", d: ["Experience", "Explode", "Explore"], p: "Explain the rule." },
        { s: "爆発する", j: "〜を爆発させる", e: "Explode", d: ["Experience", "Explain", "Explore"], p: "The bomb exploded." },
        { s: "探索する", j: "〜を調査する", e: "Explore", d: ["Experience", "Explain", "Explode"], p: "Explore the cave." },
        { s: "輸出する", j: "〜を輸出する", e: "Export", d: ["Expose", "Express", "Extend"], p: "Export cars." },
        { s: "さらす", j: "〜を暴露する", e: "Expose", d: ["Export", "Express", "Extend"], p: "Expose to light." },
        { s: "表現する", j: "〜を表現する", e: "Express", d: ["Export", "Expose", "Extend"], p: "Express feelings." },
        { s: "伸ばす", j: "〜を延長する", e: "Extend", d: ["Export", "Expose", "Express"], p: "Extend the stay." },
        { s: "向き合う", j: "顔、〜に面する", e: "Face", d: ["Fail", "Fall", "Fasten"], p: "Face the problem." },
        { s: "失敗する", j: "〜に失敗する", e: "Fail", d: ["Face", "Fall", "Fasten"], p: "Never fail." },
        { s: "落ちる", j: "落ちる", e: "Fall", d: ["Face", "Fail", "Fasten"], p: "Leaves fall." },
        { s: "留める", j: "〜をしっかり留める", e: "Fasten", d: ["Face", "Fail", "Fall"], p: "Fasten your seatbelt." },
        { s: "好む", j: "好意、〜に賛成する", e: "Favor", d: ["Fear", "Feed", "Feel"], p: "Can you do me a favor?" },
        { s: "恐れる", j: "恐怖、〜を恐れる", e: "Fear", d: ["Favor", "Feed", "Feel"], p: "Fear of heights." },
        { s: "エサをやる", j: "〜に食べ物を与える", e: "Feed", d: ["Favor", "Fear", "Feel"], p: "Feed the dog." },
        { s: "感じる", j: "〜を感じる", e: "Feel", d: ["Favor", "Fear", "Feed"], p: "Feel happy." }
    ],
    13: [
        { s: "戦う", j: "戦い、〜と戦う", e: "Fight", d: ["Fill", "Find", "Finish"], p: "Fight for peace." },
        { s: "満たす", j: "〜を満たす", e: "Fill", d: ["Fight", "Find", "Finish"], p: "Fill the bottle." },
        { s: "見つける", j: "〜を見つける", e: "Find", d: ["Fight", "Fill", "Finish"], p: "Find a key." },
        { s: "終える", j: "終わり、〜を終える", e: "Finish", d: ["Fight", "Fill", "Find"], p: "Finish the job." },
        { s: "修理する・固定", j: "〜を固定する、修理する", e: "Fix", d: ["Flash", "Float", "Flood"], p: "Fix the TV." },
        { s: "光る", j: "ひらめき、〜を光らせる", e: "Flash", d: ["Fix", "Float", "Flood"], p: "A flash of light." },
        { s: "浮く", j: "浮かぶ", e: "Float", d: ["Fix", "Flash", "Flood"], p: "Wood floats." },
        { s: "あふれる", j: "洪水、〜を溢れさせる", e: "Flood", d: ["Fix", "Flash", "Float"], p: "Flood the street." },
        { s: "流れる", j: "流れ、〜を流れる", e: "Flow", d: ["Fly", "Focus", "Follow"], p: "Rivers flow." },
        { s: "飛ぶ", j: "飛ぶ、ハエ", e: "Fly", d: ["Flow", "Focus", "Follow"], p: "Birds fly." },
        { s: "焦点を合わせる", j: "焦点、〜を集中させる", e: "Focus", d: ["Flow", "Fly", "Follow"], p: "Focus on the goal." },
        { s: "従う", j: "〜に従う、続く", e: "Follow", d: ["Flow", "Fly", "Focus"], p: "Follow the rules." },
        { s: "禁じる", j: "〜を禁止する", e: "Forbid", d: ["Force", "Forecast", "Forget"], p: "I forbid it." },
        { s: "強いる", j: "力、〜を強いる", e: "Force", d: ["Forbid", "Forecast", "Forget"], p: "By force." },
        { s: "予報する", j: "予報、〜を予測する", e: "Forecast", d: ["Forbid", "Force", "Forget"], p: "Weather forecast." },
        { s: "忘れる", j: "〜を忘れる", e: "Forget", d: ["Forbid", "Force", "Forecast"], p: "Don't forget me." },
        { s: "許す", j: "〜を許す", e: "Forgive", d: ["Form", "Found", "Freeze"], p: "Please forgive me." },
        { s: "形づくる", j: "形、〜を形成する", e: "Form", d: ["Forgive", "Found", "Freeze"], p: "Form a circle." },
        { s: "設立する", j: "〜を創立する", e: "Found", d: ["Forgive", "Form", "Freeze"], p: "Found a company." },
        { s: "凍る", j: "〜を凍らせる", e: "Freeze", d: ["Forgive", "Form", "Found"], p: "Water freezes." }
    ],
    14: [
        { s: "集まる", j: "〜を集める", e: "Gather", d: ["Gaze", "Generate", "Get"], p: "Gather information." },
        { s: "じっと見る", j: "凝視する", e: "Gaze", d: ["Gather", "Generate", "Get"], p: "Gaze at the moon." },
        { s: "生み出す", j: "〜を発生させる", e: "Generate", d: ["Gather", "Gaze", "Get"], p: "Generate power." },
        { s: "手に入れる", j: "〜を得る", e: "Get", d: ["Gather", "Gaze", "Generate"], p: "Get a ticket." },
        { s: "与える", j: "〜を与える", e: "Give", d: ["Glance", "Glow", "Go"], p: "Give me a hand." },
        { s: "ちらりと見る", j: "〜を一瞥する", e: "Glance", d: ["Give", "Glow", "Go"], p: "At a glance." },
        { s: "輝く", j: "白熱、〜を輝かせる", e: "Glow", d: ["Give", "Glance", "Go"], p: "Glow in the dark." },
        { s: "行く", j: "行く", e: "Go", d: ["Give", "Glance", "Glow"], p: "Go home." },
        { s: "統治する", j: "〜を支配する", e: "Govern", d: ["Grab", "Graduate", "Grant"], p: "Govern a country." },
        { s: "つかむ", j: "〜をひっつかむ", e: "Grab", d: ["Govern", "Graduate", "Grant"], p: "Grab a snack." },
        { s: "卒業する", j: "卒業する", e: "Graduate", d: ["Govern", "Grab", "Grant"], p: "Graduate from college." },
        { s: "認める・与える", j: "〜を許可する、与える", e: "Grant", d: ["Govern", "Grab", "Graduate"], p: "Take it for granted." },
        { s: "つかむ", j: "〜を把握する", e: "Grasp", d: ["Greet", "Grow", "Guarantee"], p: "Grasp the meaning." },
        { s: "挨拶する", j: "〜に挨拶する", e: "Greet", d: ["Grasp", "Grow", "Guarantee"], p: "Greet the guests." },
        { s: "成長する", j: "〜を育てる、育つ", e: "Grow", d: ["Grasp", "Greet", "Guarantee"], p: "Grow flowers." },
        { s: "保証する", j: "〜を保証する", e: "Guarantee", d: ["Grasp", "Greet", "Grow"], p: "Money back guarantee." },
        { s: "推測する", j: "〜を推測する", e: "Guess", d: ["Guide", "Halt", "Handle"], p: "Guess what?" },
        { s: "案内する", j: "〜を導く、ガイド", e: "Guide", d: ["Guess", "Halt", "Handle"], p: "Guide the tourists." },
        { s: "停止する", j: "〜を中止させる", e: "Halt", d: ["Guess", "Guide", "Handle"], p: "The car halted." },
        { s: "扱う", j: "〜を処理する、取っ手", e: "Handle", d: ["Guess", "Guide", "Halt"], p: "Handle with care." }
    ],
    15: [
        { s: "起こる", j: "〜が起こる", e: "Happen", d: ["Harm", "Hate", "Have"], p: "What happened?" },
        { s: "害を与える", j: "害、〜を傷つける", e: "Harm", d: ["Happen", "Hate", "Have"], p: "No harm done." },
        { s: "嫌う", j: "〜をひどく嫌う", e: "Hate", d: ["Happen", "Harm", "Have"], p: "I hate spiders." },
        { s: "持っている", j: "〜を持っている", e: "Have", d: ["Happen", "Harm", "Hate"], p: "Have a pen." },
        { s: "癒やす", j: "〜を治す", e: "Heal", d: ["Hear", "Heat", "Help"], p: "Heal the wound." },
        { s: "聞く", j: "〜が聞こえる", e: "Hear", d: ["Heal", "Heat", "Help"], p: "Hear a noise." },
        { s: "温める", j: "熱、〜を加熱する", e: "Heat", d: ["Heal", "Hear", "Help"], p: "Heat the soup." },
        { s: "助ける", j: "〜を助ける", e: "Help", d: ["Heal", "Hear", "Heat"], p: "Can I help you?" },
        { s: "ためらう", j: "〜を躊躇する", e: "Hesitate", d: ["Hide", "Hire", "Hit"], p: "Don't hesitate." },
        { s: "隠す", j: "〜を隠す", e: "Hide", d: ["Hesitate", "Hire", "Hit"], p: "Hide the truth." },
        { s: "雇う", j: "〜を雇う", e: "Hire", d: ["Hesitate", "Hide", "Hit"], p: "Hire an assistant." },
        { s: "打つ", j: "〜を打つ、当てる", e: "Hit", d: ["Hesitate", "Hide", "Hire"], p: "Hit the ball." },
        { s: "持つ・開催", j: "〜を持っている、開催する", e: "Hold", d: ["Honor", "Hope", "Hurry"], p: "Hold a meeting." },
        { s: "尊敬する", j: "名誉、〜を尊敬する", e: "Honor", d: ["Hold", "Hope", "Hurry"], p: "It's an honor." },
        { s: "望む", j: "希望、〜を望む", e: "Hope", d: ["Hold", "Honor", "Hurry"], p: "I hope so." },
        { s: "急ぐ", j: "〜を急がせる", e: "Hurry", d: ["Hold", "Honor", "Hope"], p: "Hurry up." },
        { s: "傷つける", j: "〜を傷つける、痛む", e: "Hurt", d: ["Identify", "Ignore", "Illustrate"], p: "My leg hurts." },
        { s: "特定する", j: "〜を特定する", e: "Identify", d: ["Hurt", "Ignore", "Illustrate"], p: "Identify the person." },
        { s: "無視する", j: "〜を無視する", e: "Ignore", d: ["Hurt", "Identify", "Illustrate"], p: "Ignore the noise." },
        { s: "説明する（図）", j: "〜を例証する", e: "Illustrate", d: ["Hurt", "Identify", "Ignore"], p: "Illustrate the case." }
    ],
        16: [
        { s: "想像する", j: "〜を想像する", e: "Imagine", d: ["Imitate", "Imply", "Import"], p: "Imagine your future." },
        { s: "真似る", j: "〜を模倣する", e: "Imitate", d: ["Imagine", "Imply", "Import"], p: "Imitate the teacher." },
        { s: "暗示する", j: "〜を暗に意味する", e: "Imply", d: ["Imagine", "Imitate", "Import"], p: "What do you imply?" },
        { s: "輸入する", j: "〜を輸入する", e: "Import", d: ["Imagine", "Imitate", "Imply"], p: "Import coffee." },
        { s: "感銘を与える", j: "〜を感動させる", e: "Impress", d: ["Improve", "Include", "Increase"], p: "Impress the audience." },
        { s: "向上させる", j: "〜を改善する", e: "Improve", d: ["Impress", "Include", "Increase"], p: "Improve your health." },
        { s: "含む", j: "〜を含んでいる", e: "Include", d: ["Impress", "Improve", "Increase"], p: "Tax is included." },
        { s: "増やす", j: "〜を増加させる", e: "Increase", d: ["Impress", "Improve", "Include"], p: "Increase the speed." },
        { s: "示す", j: "〜を指し示す", e: "Indicate", d: ["Inform", "Inherit", "Inject"], p: "Indicate the position." },
        { s: "知らせる", j: "〜に通知する", e: "Inform", d: ["Indicate", "Inherit", "Inject"], p: "Inform the police." },
        { s: "受け継ぐ", j: "〜を相続する", e: "Inherit", d: ["Indicate", "Inform", "Inject"], p: "Inherit a fortune." },
        { s: "注射する", j: "〜を注入する", e: "Inject", d: ["Indicate", "Inform", "Inherit"], p: "Inject medicine." },
        { s: "傷つける", j: "〜に怪我をさせる", e: "Injure", d: ["Inquire", "Insert", "Insist"], p: "Injure the knee." },
        { s: "尋ねる", j: "〜を問い合わせる", e: "Inquire", d: ["Injure", "Insert", "Insist"], p: "Inquire about the price." },
        { s: "差し込む", j: "〜を挿入する", e: "Insert", d: ["Injure", "Inquire", "Insist"], p: "Insert the card." },
        { s: "主張する", j: "〜を言い張る", e: "Insist", d: ["Injure", "Inquire", "Insert"], p: "Insist on the truth." },
        { s: "点検する", j: "〜を検査する", e: "Inspect", d: ["Inspire", "Install", "Instruct"], p: "Inspect the factory." },
        { s: "奮い立たせる", j: "〜に刺激を与える", e: "Inspire", d: ["Inspect", "Install", "Instruct"], p: "Inspire the team." },
        { s: "設置する", j: "〜を取り付ける", e: "Install", d: ["Inspect", "Inspire", "Instruct"], p: "Install the software." },
        { s: "教える", j: "〜を指示・教育する", e: "Instruct", d: ["Inspect", "Inspire", "Install"], p: "Instruct the class." }
    ],
    17: [
        { s: "意図する", j: "〜するつもりだ", e: "Intend", d: ["Interact", "Interest", "Interfere"], p: "I intend to go." },
        { s: "交流する", j: "〜と相互に作用する", e: "Interact", d: ["Intend", "Interest", "Interfere"], p: "Interact with kids." },
        { s: "興味を持たせる", j: "興味、〜に興味を持たせる", e: "Interest", d: ["Intend", "Interact", "Interfere"], p: "Of interest." },
        { s: "邪魔する", j: "〜を妨げる・干渉する", e: "Interfere", d: ["Intend", "Interact", "Interest"], p: "Don't interfere." },
        { s: "解釈する", j: "〜を解釈する", e: "Interpret", d: ["Interrupt", "Introduce", "Invade"], p: "Interpret the data." },
        { s: "中断させる", j: "〜を遮る", e: "Interrupt", d: ["Interpret", "Introduce", "Invade"], p: "Don't interrupt me." },
        { s: "紹介・導入", j: "〜を紹介する", e: "Introduce", d: ["Interpret", "Interrupt", "Invade"], p: "Introduce a friend." },
        { s: "侵略する", j: "〜に侵入する", e: "Invade", d: ["Interpret", "Interrupt", "Introduce"], p: "Invade the privacy." },
        { s: "発明する", j: "〜を発明する", e: "Invent", d: ["Invest", "Investigate", "Invite"], p: "Invent a gadget." },
        { s: "投資する", j: "〜を投資する", e: "Invest", d: ["Invent", "Investigate", "Invite"], p: "Invest in stocks." },
        { s: "調査する", j: "〜を調査する", e: "Investigate", d: ["Invent", "Invest", "Invite"], p: "Investigate the crime." },
        { s: "招待する", j: "〜を招く", e: "Invite", d: ["Invent", "Invest", "Investigate"], p: "Invite you to dinner." },
        { s: "関わらせる", j: "〜を巻き込む", e: "Involve", d: ["Iron", "Isolate", "Issue"], p: "Don't involve me." },
        { s: "アイロン・鉄", j: "鉄、〜にアイロンをかける", e: "Iron", d: ["Involve", "Isolate", "Issue"], p: "Iron the shirt." },
        { s: "隔離する", j: "〜を孤立させる", e: "Isolate", d: ["Involve", "Iron", "Issue"], p: "Isolate the patient." },
        { s: "出す・問題", j: "問題、〜を発行する", e: "Issue", d: ["Involve", "Iron", "Isolate"], p: "Issue a passport." },
        { s: "かゆい", j: "かゆみ、〜がかゆくなる", e: "Itch", d: ["Itemize", "Jack", "Jam"], p: "My eye itches." },
        { s: "項目別に記す", j: "〜を明細に記す", e: "Itemize", d: ["Itch", "Jack", "Jam"], p: "Itemize the bill." },
        { s: "持ち上げる", j: "ジャッキ、〜を持ち上げる", e: "Jack", d: ["Itch", "Itemize", "Jam"], p: "Jack up the car." },
        { s: "詰め込む", j: "渋滞、〜を詰め込む", e: "Jam", d: ["Itch", "Itemize", "Jack"], p: "Traffic jam." }
    ],
    18: [
        { s: "じろじろ見る", j: "〜をあざける", e: "Jeer", d: ["Jog", "Join", "Joke"], p: "Don't jeer at him." },
        { s: "ジョギングする", j: "ゆっくり走る", e: "Jog", d: ["Jeer", "Join", "Joke"], p: "Jog every morning." },
        { s: "加わる", j: "〜に参加する", e: "Join", d: ["Jeer", "Jog", "Joke"], p: "Join the club." },
        { s: "冗談を言う", j: "冗談、〜をからかう", e: "Joke", d: ["Jeer", "Jog", "Join"], p: "It's a joke." },
        { s: "判断する", j: "〜を判断する、審判", e: "Judge", d: ["Jump", "Justify", "Keep"], p: "Don't judge by looks." },
        { s: "跳ぶ", j: "跳ぶ、ジャンプ", e: "Jump", d: ["Judge", "Justify", "Keep"], p: "Jump high." },
        { s: "正当化する", j: "〜を正当化する", e: "Justify", d: ["Judge", "Jump", "Keep"], p: "Justify the action." },
        { s: "保つ", j: "〜を持ち続ける", e: "Keep", d: ["Judge", "Jump", "Justify"], p: "Keep the secret." },
        { s: "蹴る", j: "〜を蹴る", e: "Kick", d: ["Kidnap", "Kill", "Kiss"], p: "Kick the ball." },
        { s: "誘拐する", j: "〜を誘拐する", e: "Kidnap", d: ["Kick", "Kill", "Kiss"], p: "Kidnap a child." },
        { s: "殺す", j: "〜を殺す", e: "Kill", d: ["Kick", "Kidnap", "Kiss"], p: "Kill time." },
        { s: "キスする", j: "〜にキスする", e: "Kiss", d: ["Kick", "Kidnap", "Kill"], p: "Kiss my hand." },
        { s: "ひざまずく", j: "ひざまずく", e: "Kneel", d: ["Knit", "Knock", "Know"], p: "Kneel on the floor." },
        { s: "編む", j: "〜を編む", e: "Knit", d: ["Kneel", "Knock", "Know"], p: "Knit a sweater." },
        { s: "叩く", j: "〜をノックする", e: "Knock", d: ["Kneel", "Knit", "Know"], p: "Knock on the door." },
        { s: "知っている", j: "〜を知っている", e: "Know", d: ["Kneel", "Knit", "Knock"], p: "I know that." },
        { s: "ラベルを貼る", j: "〜にラベルを貼る", e: "Label", d: ["Lack", "Land", "Last"], p: "Label the box." },
        { s: "欠いている", j: "〜が不足している", e: "Lack", d: ["Label", "Land", "Last"], p: "Lack of sleep." },
        { s: "着陸する", j: "陸、着陸する", e: "Land", d: ["Label", "Lack", "Last"], p: "The plane landed." },
        { s: "続く", j: "最後の、〜が続く", e: "Last", d: ["Label", "Lack", "Land"], p: "It lasts forever." }
    ],
    19: [
        { s: "笑う", j: "（声を上げて）笑う", e: "Laugh", d: ["Launch", "Lay", "Lead"], p: "Laugh out loud." },
        { s: "開始する", j: "〜を打ち上げる・開始する", e: "Launch", d: ["Laugh", "Lay", "Lead"], p: "Launch a website." },
        { s: "横たえる", j: "〜を置く、横たえる", e: "Lay", d: ["Laugh", "Launch", "Lead"], p: "Lay the baby down." },
        { s: "導く", j: "〜をリードする、導く", e: "Lead", d: ["Laugh", "Launch", "Lay"], p: "Lead the way." },
        { s: "漏れる", j: "漏れ、漏れる", e: "Leak", d: ["Lean", "Learn", "Leave"], p: "The roof leaks." },
        { s: "傾く・寄りかかる", j: "寄りかかる、傾く", e: "Lean", d: ["Leak", "Learn", "Leave"], p: "Lean against the wall." },
        { s: "学ぶ", j: "〜を学ぶ", e: "Learn", d: ["Leak", "Lean", "Leave"], p: "Learn English." },
        { s: "出発する・残す", j: "〜を去る、残す", e: "Leave", d: ["Leak", "Lean", "Learn"], p: "Leave me alone." },
        { s: "講義する", j: "講義、〜を講義する", e: "Lecture", d: ["Lend", "Lengthen", "Lessen"], p: "A boring lecture." },
        { s: "貸す", j: "〜を貸す", e: "Lend", d: ["Lecture", "Lengthen", "Lessen"], p: "Lend me a pen." },
        { s: "長くする", j: "〜を長くする", e: "Lengthen", d: ["Lecture", "Lend", "Lessen"], p: "Lengthen the rope." },
        { s: "減らす", j: "〜を少なくする", e: "Lessen", d: ["Lecture", "Lend", "Lengthen"], p: "Lessen the pain." },
        { s: "〜させる", j: "〜させる", e: "Let", d: ["Level", "Lick", "Lie"], p: "Let it go." },
        { s: "平らにする", j: "水準、〜を平らにする", e: "Level", d: ["Let", "Lick", "Lie"], p: "On a level surface." },
        { s: "なめる", j: "〜をなめる", e: "Lick", d: ["Let", "Level", "Lie"], p: "The cat licks it." },
        { s: "横になる・嘘", j: "横たわる、嘘をつく", e: "Lie", d: ["Let", "Level", "Lick"], p: "Lie on the bed." },
        { s: "持ち上げる", j: "〜を持ち上げる", e: "Lift", d: ["Light", "Like", "Limit"], p: "Lift the box." },
        { s: "照らす", j: "光、〜を照らす", e: "Light", d: ["Lift", "Like", "Limit"], p: "Turn on the light." },
        { s: "好む", j: "〜を好む、〜のような", e: "Like", d: ["Lift", "Light", "Limit"], p: "I like it." },
        { s: "制限する", j: "制限、〜を限る", e: "Limit", d: ["Lift", "Light", "Like"], p: "Speed limit." }
    ],
    20: [
        { s: "線を引く", j: "線、〜に裏地をつける", e: "Line", d: ["Link", "List", "Listen"], p: "Stand in line." },
        { s: "つなぐ", j: "関連、〜をつなぐ", e: "Link", d: ["Line", "List", "Listen"], p: "Link the pages." },
        { s: "表にする", j: "表、〜をリストにする", e: "List", d: ["Line", "Link", "Listen"], p: "Price list." },
        { s: "聴く", j: "（意識して）聴く", e: "Listen", d: ["Line", "Link", "List"], p: "Listen to music." },
        { s: "住む", j: "住む、生きる", e: "Live", d: ["Load", "Loan", "Locate"], p: "Live in Japan." },
        { s: "積む", j: "荷、〜を積む", e: "Load", d: ["Live", "Loan", "Locate"], p: "Load the truck." },
        { s: "貸し付ける", j: "ローン、〜を貸す", e: "Loan", d: ["Live", "Load", "Locate"], p: "Take out a loan." },
        { s: "場所を突き止める", j: "〜を置く、探し出す", e: "Locate", d: ["Live", "Load", "Loan"], p: "Locate the office." },
        { s: "鍵をかける", j: "錠、〜を固定する", e: "Lock", d: ["Log", "Look", "Lose"], p: "Lock the door." },
        { s: "記録する", j: "丸太、〜を記録する", e: "Log", d: ["Lock", "Look", "Lose"], p: "Log in." },
        { s: "見る", j: "見る、〜に見える", e: "Look", d: ["Lock", "Log", "Lose"], p: "Look at me." },
        { s: "失う", j: "〜をなくす、負ける", e: "Lose", d: ["Lock", "Log", "Look"], p: "Lose my way." },
        { s: "愛する", j: "〜を愛する", e: "Love", d: ["Lower", "Lull", "Lumber"], p: "I love you." },
        { s: "下げる", j: "より低い、〜を下げる", e: "Lower", d: ["Love", "Lull", "Lumber"], p: "Lower the price." },
        { s: "あやす", j: "〜をなだめる", e: "Lull", d: ["Love", "Lower", "Lumber"], p: "Lullaby." },
        { s: "ドタバタ歩く", j: "〜をのろのろ歩く", e: "Lumber", d: ["Love", "Lower", "Lull"], p: "Lumbering along." },
        { s: "昼食をとる", j: "昼食を食べる", e: "Lunch", d: ["Lure", "Lurk", "Lust"], p: "Let's have lunch." },
        { s: "誘惑する", j: "〜を誘い出す", e: "Lure", d: ["Lunch", "Lurk", "Lust"], p: "Lure the fish." },
        { s: "潜む", j: "潜伏する", e: "Lurk", d: ["Lunch", "Lure", "Lust"], p: "Lurk in shadows." },
        { s: "熱望する", j: "切望する", e: "Lust", d: ["Lunch", "Lure", "Lurk"], p: "Lust for power." }
    ],
        21: [
        { s: "作る", j: "〜を作る", e: "Make", d: ["Manage", "Mark", "Marry"], p: "Make a cake." },
        { s: "管理する", j: "〜を何とかやり遂げる", e: "Manage", d: ["Make", "Mark", "Marry"], p: "Manage time." },
        { s: "印をつける", j: "印、〜を採点する", e: "Mark", d: ["Make", "Manage", "Marry"], p: "Mark the calendar." },
        { s: "結婚する", j: "〜と結婚する", e: "Marry", d: ["Make", "Manage", "Mark"], p: "Marry her." },
        { s: "匹敵する", j: "試合、〜と調和する", e: "Match", d: ["Matter", "Mean", "Measure"], p: "Good match." },
        { s: "重要である", j: "事柄、〜が重要だ", e: "Matter", d: ["Match", "Mean", "Measure"], p: "It doesn't matter." },
        { s: "意味する", j: "〜を意味する、ケチな", e: "Mean", d: ["Match", "Matter", "Measure"], p: "What do you mean?" },
        { s: "測る", j: "寸法、〜を測定する", e: "Measure", d: ["Match", "Matter", "Mean"], p: "Measure the room." },
        { s: "会う", j: "〜に会う", e: "Meet", d: ["Melt", "Memorize", "Mend"], p: "Nice to meet you." },
        { s: "溶ける", j: "〜を溶かす", e: "Melt", d: ["Meet", "Memorize", "Mend"], p: "Snow melts." },
        { s: "暗記する", j: "〜を記憶する", e: "Memorize", d: ["Meet", "Melt", "Mend"], p: "Memorize the poem." },
        { s: "直す", j: "〜を繕う、修理する", e: "Mend", d: ["Meet", "Melt", "Memorize"], p: "Mend the socks." },
        { s: "言う", j: "〜に言及する", e: "Mention", d: ["Merge", "Mess", "Mind"], p: "Don't mention it." },
        { s: "合併する", j: "〜を併合する", e: "Merge", d: ["Mention", "Mess", "Mind"], p: "Merge the files." },
        { s: "散らかす", j: "混乱、〜を汚す", e: "Mess", d: ["Mention", "Merge", "Mind"], p: "Messy room." },
        { s: "気にする", j: "心、〜を気にする", e: "Mind", d: ["Mention", "Merge", "Mess"], p: "Never mind." },
        { s: "逃す・恋しがる", j: "〜を逃す、寂しく思う", e: "Miss", d: ["Mistake", "Mix", "Model"], p: "I miss you." },
        { s: "間違える", j: "間違い、〜を誤解する", e: "Mistake", d: ["Miss", "Mix", "Model"], p: "By mistake." },
        { s: "混ぜる", j: "〜を混ぜる", e: "Mix", d: ["Miss", "Mistake", "Model"], p: "Mix the colors." },
        { s: "手本にする", j: "型、〜をモデルにする", e: "Model", d: ["Miss", "Mistake", "Mix"], p: "Role model." }
    ],
    22: [
        { s: "監視する", j: "モニター、〜を監視する", e: "Monitor", d: ["Move", "Multiply", "Murder"], p: "Monitor the screen." },
        { s: "動く", j: "動く、引っ越す", e: "Move", d: ["Monitor", "Multiply", "Murder"], p: "Move to Osaka." },
        { s: "増やす", j: "〜を増やす、掛ける", e: "Multiply", d: ["Monitor", "Move", "Murder"], p: "Multiplied by two." },
        { s: "殺害する", j: "殺人、〜を殺す", e: "Murder", d: ["Monitor", "Move", "Multiply"], p: "Murder case." },
        { s: "つぶやく", j: "〜を小声で言う", e: "Murmur", d: ["Must", "Mutter", "Name"], p: "Murmur to oneself." },
        { s: "〜しなければならない", j: "〜に違いない", e: "Must", d: ["Murmur", "Mutter", "Name"], p: "I must go." },
        { s: "ぼそぼそ言う", j: "つぶやく", e: "Mutter", d: ["Murmur", "Must", "Name"], p: "Stop muttering." },
        { s: "名付ける", j: "名前、〜と命名する", e: "Name", d: ["Murmur", "Must", "Mutter"], p: "Name the baby." },
        { s: "必要とする", j: "〜が必要だ", e: "Need", d: ["Neglect", "Negotiate", "Nod"], p: "I need help." },
        { s: "怠る", j: "〜を無視する、放置する", e: "Neglect", d: ["Need", "Negotiate", "Nod"], p: "Neglect duties." },
        { s: "交渉する", j: "交渉する", e: "Negotiate", d: ["Need", "Neglect", "Nod"], p: "Negotiate the price." },
        { s: "うなずく", j: "うなずく", e: "Nod", d: ["Need", "Neglect", "Negotiate"], p: "Nod in agreement." },
        { s: "指名する", j: "〜を推薦する", e: "Nominate", d: ["Note", "Notice", "Notify"], p: "Nominate for Oscar." },
        { s: "書き留める", j: "メモ、〜に注意する", e: "Note", d: ["Nominate", "Notice", "Notify"], p: "Take a note." },
        { s: "気づく", j: "掲示、〜に気づく", e: "Notice", d: ["Nominate", "Note", "Notify"], p: "Notice the change." },
        { s: "知らせる", j: "〜に通知する", e: "Notify", d: ["Nominate", "Note", "Notice"], p: "Notify the winner." },
        { s: "数える", j: "〜を番号づける", e: "Number", d: ["Nurse", "Obey", "Object"], p: "Number the pages." },
        { s: "看病する", j: "看護師、〜を看護する", e: "Nurse", d: ["Number", "Obey", "Object"], p: "Nurse the sick." },
        { s: "従う", j: "〜に従う", e: "Obey", d: ["Number", "Nurse", "Object"], p: "Obey the law." },
        { s: "反対する", j: "物体、〜に反対する", e: "Object", d: ["Number", "Nurse", "Obey"], p: "I object!" }
    ],
    23: [
        { s: "観察する", j: "〜を観察する", e: "Observe", d: ["Obtain", "Occupy", "Occur"], p: "Observe nature." },
        { s: "手に入れる", j: "〜を獲得する", e: "Obtain", d: ["Observe", "Occupy", "Occur"], p: "Obtain a license." },
        { s: "占める", j: "〜を占有する", e: "Occupy", d: ["Observe", "Obtain", "Occur"], p: "Occupy the room." },
        { s: "起こる", j: "〜が生じる", e: "Occur", d: ["Observe", "Obtain", "Occupy"], p: "A problem occurred." },
        { s: "提供する", j: "〜を申し出る、提供", e: "Offer", d: ["Omit", "Open", "Operate"], p: "Offer some help." },
        { s: "省く", j: "〜を除外する", e: "Omit", d: ["Offer", "Open", "Operate"], p: "Omit the details." },
        { s: "開ける", j: "開いている、〜を開く", e: "Open", d: ["Offer", "Omit", "Operate"], p: "Open the window." },
        { s: "操作する", j: "〜を動かす、手術する", e: "Operate", d: ["Offer", "Omit", "Open"], p: "Operate a machine." },
        { s: "反対する", j: "〜に反対・対抗する", e: "Oppose", d: ["Order", "Organize", "Overcome"], p: "Oppose the plan." },
        { s: "注文する・命令", j: "順序、〜を注文する", e: "Order", d: ["Oppose", "Organize", "Overcome"], p: "Order pizza." },
        { s: "整理・組織する", j: "〜を準備・整理する", e: "Organize", d: ["Oppose", "Order", "Overcome"], p: "Organize a party." },
        { s: "克服する", j: "〜に打ち勝つ", e: "Overcome", d: ["Oppose", "Order", "Organize"], p: "Overcome fear." },
        { s: "負う", j: "〜に借金がある", e: "Owe", d: ["Own", "Pack", "Paint"], p: "I owe you one." },
        { s: "所有する", j: "自分自身の、〜を所有する", e: "Own", d: ["Owe", "Pack", "Paint"], p: "Own a car." },
        { s: "荷造りする", j: "包み、〜を梱包する", e: "Pack", d: ["Owe", "Own", "Paint"], p: "Pack the suitcase." },
        { s: "塗る", j: "絵の具、〜を塗る", e: "Paint", d: ["Owe", "Own", "Pack"], p: "Paint the wall." },
        { s: "駐車する", j: "公園、〜を駐車する", e: "Park", d: ["Participate", "Pass", "Pause"], p: "No parking." },
        { s: "参加する", j: "〜に参加する", e: "Participate", d: ["Park", "Pass", "Pause"], p: "Participate in sports." },
        { s: "通る・渡す", j: "〜を通過する、渡す", e: "Pass", d: ["Park", "Participate", "Pause"], p: "Pass the exam." },
        { s: "一時停止する", j: "休止、〜を中断する", e: "Pause", d: ["Park", "Participate", "Pass"], p: "Push pause." }
    ],
    24: [
        { s: "払う", j: "〜を支払う", e: "Pay", d: ["Perceive", "Perform", "Permit"], p: "Pay by card." },
        { s: "知覚する", j: "〜に気づく", e: "Perceive", d: ["Pay", "Perform", "Permit"], p: "Perceive the danger." },
        { s: "演じる・行う", j: "〜を実行する、演じる", e: "Perform", d: ["Pay", "Perceive", "Permit"], p: "Perform on stage." },
        { s: "許可する", j: "許可証、〜を許す", e: "Permit", d: ["Pay", "Perceive", "Perform"], p: "Parking permit." },
        { s: "説得する", j: "〜を納得させる", e: "Persuade", d: ["Pick", "Place", "Plan"], p: "Persuade him." },
        { s: "選ぶ・摘む", j: "〜を選ぶ、摘む", e: "Pick", d: ["Persuade", "Place", "Plan"], p: "Pick flowers." },
        { s: "置く", j: "場所、〜を置く", e: "Place", d: ["Persuade", "Pick", "Plan"], p: "A quiet place." },
        { s: "計画する", j: "計画、〜を予定する", e: "Plan", d: ["Persuade", "Pick", "Place"], p: "Make a plan." },
        { s: "植える", j: "植物、〜を植える", e: "Plant", d: ["Play", "Please", "Point"], p: "Plant a tree." },
        { s: "遊ぶ・演奏", j: "〜を演奏する、遊ぶ", e: "Play", d: ["Plant", "Please", "Point"], p: "Play the piano." },
        { s: "喜ばせる", j: "〜を喜ばせる、どうぞ", e: "Please", d: ["Plant", "Play", "Point"], p: "Yes, please." },
        { s: "指さす", j: "点、〜を指し示す", e: "Point", d: ["Plant", "Play", "Please"], p: "What's the point?" },
        { s: "磨く", j: "〜を磨く、洗練させる", e: "Polish", d: ["Pollute", "Pose", "Possess"], p: "Polish the shoes." },
        { s: "汚染する", j: "〜を汚す", e: "Pollute", d: ["Polish", "Pose", "Possess"], p: "Pollute the air." },
        { s: "ポーズをとる", j: "姿勢、〜を提起する", e: "Pose", d: ["Polish", "Pollute", "Possess"], p: "Pose for a photo." },
        { s: "持っている", j: "〜を所有する", e: "Possess", d: ["Polish", "Pollute", "Pose"], p: "Possess a gun." },
        { s: "延期する", j: "〜を後に延ばす", e: "Postpone", d: ["Pour", "Practice", "Praise"], p: "Postpone the match." },
        { s: "注ぐ", j: "〜を注ぐ、流れる", e: "Pour", d: ["Postpone", "Practice", "Praise"], p: "Pour the tea." },
        { s: "練習する", j: "練習、〜を実行する", e: "Practice", d: ["Postpone", "Pour", "Praise"], p: "Practice makes perfect." },
        { s: "ほめる", j: "賞賛、〜をほめる", e: "Praise", d: ["Postpone", "Pour", "Practice"], p: "Praise the student." }
    ],
    25: [
        { s: "祈る", j: "〜を祈る", e: "Pray", d: ["Predict", "Prefer", "Prepare"], p: "Pray for peace." },
        { s: "予測する", j: "〜を予言する", e: "Predict", d: ["Pray", "Prefer", "Prepare"], p: "Predict the future." },
        { s: "好む", j: "〜の方を好む", e: "Prefer", d: ["Pray", "Predict", "Prepare"], p: "I prefer tea." },
        { s: "準備する", j: "〜を用意する", e: "Prepare", d: ["Pray", "Predict", "Prefer"], p: "Prepare for exam." },
        { s: "贈る・現在", j: "現在の、贈り物、〜を贈る", e: "Present", d: ["Preserve", "Press", "Pretend"], p: "At present." },
        { s: "保存する", j: "〜を保護・維持する", e: "Preserve", d: ["Present", "Press", "Pretend"], p: "Preserve nature." },
        { s: "押す", j: "〜を押す、出版", e: "Press", d: ["Present", "Preserve", "Pretend"], p: "Press the button." },
        { s: "ふりをする", j: "〜のふりをする", e: "Pretend", d: ["Present", "Preserve", "Press"], p: "Pretend to sleep." },
        { s: "防ぐ", j: "〜を妨げる・予防する", e: "Prevent", d: ["Print", "Proceed", "Produce"], p: "Prevent accidents." },
        { s: "印刷する", j: "〜を印刷する", e: "Print", d: ["Prevent", "Proceed", "Produce"], p: "Print the document." },
        { s: "進む", j: "続行する、進む", e: "Proceed", d: ["Prevent", "Print", "Produce"], p: "Proceed to Gate 5." },
        { s: "生産する", j: "〜を作る、農産物", e: "Produce", d: ["Prevent", "Print", "Proceed"], p: "Produce organic food." },
        { s: "約束する", j: "約束、〜を約束する", e: "Promise", d: ["Promote", "Pronounce", "Protect"], p: "Keep a promise." },
        { s: "促進・昇進", j: "〜を促進・昇進させる", e: "Promote", d: ["Promise", "Pronounce", "Protect"], p: "Promote the sales." },
        { s: "発音する", j: "〜を発音する", e: "Pronounce", d: ["Promise", "Promote", "Protect"], p: "How to pronounce it?" },
        { s: "守る", j: "〜を保護する", e: "Protect", d: ["Promise", "Promote", "Pronounce"], p: "Protect the environment." },
        { s: "証明する", j: "〜を証明する、判明する", e: "Prove", d: ["Provide", "Publish", "Pull"], p: "Prove the theory." },
        { s: "提供する", j: "〜を供給・用意する", e: "Provide", d: ["Prove", "Publish", "Pull"], p: "Provide information." },
        { s: "出版する", j: "〜を発行・公表する", e: "Publish", d: ["Prove", "Provide", "Pull"], p: "Publish a book." },
        { s: "引く", j: "〜を引く", e: "Pull", d: ["Prove", "Provide", "Publish"], p: "Pull the door." }
    ]
};

